export const categoryMap = new Map([ 
    [
        "US", new Map(Object.entries({
            "Lebanese": "lebanese",
            "Cafes": "cafes",
            "Caribbean": "caribbean",
            "Salad": "salad",
            "Polynesian": "polynesian",
            "Japanese": "japanese",
            "German": "german",
            "Shaved Snow": "shavedsnow",
            "Tacos": "tacos",
            "Breakfast & Brunch": "breakfast_brunch",
            "Belgian": "belgian",
            "Do-It-Yourself Food": "diyfood",
            "Vegan": "vegan",
            "Acai Bowls": "acaibowls",
            "Wineries": "wineries",
            "Australian": "australian",
            "Mexican": "mexican",
            "Creperies": "creperies",
            "Coffee & Tea": "coffee",
            "Southern": "southern",
            "Mediterranean": "mediterranean",
            "Custom Cakes": "customcakes",
            "Szechuan": "szechuan",
            "Organic Stores": "organic_stores",
            "Sicilian": "sicilian",
            "Seafood Markets": "seafoodmarkets",
            "Chinese": "chinese",
            "Kebab": "kebab",
            "Kosher": "kosher",
            "Fondue": "fondue",
            "Cupcakes": "cupcakes",
            "Hainan": "hainan",
            "Pretzels": "pretzels",
            "CSA": "csa",
            "Georgian": "georgian",
            "Izakaya": "izakaya",
            "Fish & Chips": "fishnchips",
            "Food": "food",
            "Empanadas": "empanadas",
            "Fast Food": "hotdogs",
            "Meat Shops": "meats",
            "Poutineries": "poutineries",
            "Syrian": "syrian",
            "Hot Dogs": "hotdog",
            "Shanghainese": "shanghainese",
            "Cantonese": "cantonese",
            "Butcher": "butcher",
            "Egyptian": "egyptian",
            "Russian": "russian",
            "Food Delivery Services": "fooddeliveryservices",
            "Food Stands": "foodstands",
            "Pakistani": "pakistani",
            "Basque": "basque",
            "Burmese": "burmese",
            "Breweries": "breweries",
            "International Grocery": "intlgrocery",
            "Kombucha": "kombucha",
            "Restaurants": "restaurants",
            "Portuguese": "portuguese",
            "Vegetarian": "vegetarian",
            "Smokehouse": "smokehouse",
            "Piadina": "piadina",
            "Wine Tasting Room": "winetastingroom",
            "South African": "southafrican",
            "Italian": "italian",
            "Food Trucks": "foodtrucks",
            "Chocolatiers & Shops": "chocolate",
            "Pancakes": "pancakes",
            "Ethiopian": "ethiopian",
            "Japanese Curry": "japacurry",
            "Beer, Wine & Spirits": "beer_and_wine",
            "Slovakian": "slovakian",
            "Grocery": "grocery",
            "Ramen": "ramen",
            "Tuscan": "tuscan",
            "Afghan": "afghani",
            "Scandinavian": "scandinavian",
            "African": "african",
            "Barbeque": "bbq",
            "Brasseries": "brasseries",
            "Reunion": "reunion",
            "Uzbek": "uzbek",
            "Steakhouses": "steak",
            "Sandwiches": "sandwiches",
            "Somali": "somali",
            "Candy Stores": "candy",
            "Filipino": "filipino",
            "Convenience Stores": "convenience",
            "Singaporean": "singaporean",
            "Honey": "honey",
            "Pan Asian": "panasian",
            "Latin American": "latin",
            "Coffee Roasteries": "coffeeroasteries",
            "Nicaraguan": "nicaraguan",
            "Juice Bars & Smoothies": "juicebars",
            "Bulgarian": "bulgarian",
            "Shaved Ice": "shavedice",
            "Street Vendors": "streetvendors",
            "Brazilian": "brazilian",
            "Desserts": "desserts",
            "Cideries": "cideries",
            "Hong Kong Style Cafe": "hkcafe",
            "Dinner Theater": "dinnertheater",
            "Colombian": "colombian",
            "Distilleries": "distilleries",
            "Eritrean": "eritrean",
            "Turkish": "turkish",
            "Game Meat": "gamemeat",
            "Bubble Tea": "bubbletea",
            "Falafel": "falafel",
            "Chimney Cakes": "chimneycakes",
            "Tea Rooms": "tea",
            "Specialty Food": "gourmet",
            "Food Court": "food_court",
            "Senegalese": "senegalese",
            "Farmers Market": "farmersmarket",
            "Dominican": "dominican",
            "Nepalese": "himalayan",
            "Salvadoran": "salvadoran",
            "New Mexican Cuisine": "newmexican",
            "Hungarian": "hungarian",
            "Laotian": "laotian",
            "Macarons": "macarons",
            "British": "british",
            "French": "french",
            "Taiwanese": "taiwanese",
            "Pop-Up Restaurants": "popuprestaurants",
            "Ice Cream & Frozen Yogurt": "icecream",
            "Poke": "poke",
            "Dim Sum": "dimsum",
            "Ukrainian": "ukrainian",
            "Gelato": "gelato",
            "Greek": "greek",
            "Arabic": "arabian",
            "Cake Shop": "cakeshop",
            "Delis": "delis",
            "Scottish": "scottish",
            "Mauritius": "mauritius",
            "Iranian": "persian",
            "Indonesian": "indonesian",
            "Austrian": "austrian",
            "Trinidadian": "trinidadian",
            "Waffles": "waffles",
            "Themed Cafes": "themedcafes",
            "Calabrian": "calabrian",
            "Beverage Store": "beverage_stores",
            "Donuts": "donuts",
            "Imported Food": "importedfood",
            "American (Traditional)": "tradamerican",
            "Creole": "cajun",
            "Czech": "czech",
            "Iberian": "iberian",
            "Mongolian": "mongolian",
            "Noodles": "noodles",
            "Seafood": "seafood",
            "Wraps": "wraps",
            "Armenian": "armenian",
            "Gastropubs": "gastropubs",
            "Gluten-Free": "gluten_free",
            "Meaderies": "meaderies",
            "Spanish": "spanish",
            "Pasta Shops": "pastashops",
            "Peruvian": "peruvian",
            "Hawaiian": "hawaiian",
            "Supper Clubs": "supperclubs",
            "Honduran": "honduran",
            "Popcorn Shops": "popcorn",
            "Asian Fusion": "asianfusion",
            "Bangladeshi": "bangladeshi",
            "Small Plates": "tapasmallplates",
            "Thai": "thai",
            "Tapas Bars": "tapas",
            "Health Markets": "healthmarkets",
            "Modern European": "modern_european",
            "Puerto Rican": "puertorican",
            "Middle Eastern": "mideastern",
            "Diners": "diners",
            "Buffets": "buffets",
            "Indian": "indpak",
            "Chicken Shop": "chickenshop",
            "Guamanian": "guamanian",
            "Raw Food": "raw_food",
            "Cambodian": "cambodian",
            "Water Stores": "waterstores",
            "Brewpubs": "brewpubs",
            "Cheese Shops": "cheese",
            "American (New)": "newamerican",
            "Chicken Wings": "chicken_wings",
            "Polish": "polish",
            "Korean": "korean",
            "Pizza": "pizza",
            "Sardinian": "sardinian",
            "Olive Oil": "oliveoil",
            "Comfort Food": "comfortfood",
            "Conveyor Belt Sushi": "conveyorsushi",
            "Venezuelan": "venezuelan",
            "Argentine": "argentine",
            "Cheesesteaks": "cheesesteaks",
            "Irish": "irish",
            "Sushi Bars": "sushi",
            "Cuban": "cuban",
            "Herbs & Spices": "herbsandspices",
            "Teppanyaki": "teppanyaki",
            "Moroccan": "moroccan",
            "Soup": "soup",
            "Vietnamese": "vietnamese",
            "Bagels": "bagels",
            "Halal": "halal",
            "Soul Food": "soulfood",
            "Hot Pot": "hotpot",
            "Haitian": "haitian",
            "Cafeteria": "cafeteria",
            "Burgers": "burgers",
            "Internet Cafes": "internetcafe",
            "Bakeries": "bakeries",
            "Malaysian": "malaysian",
            "Sri Lankan": "srilankan",
            "Catalan": "catalan",
            "Fruits & Veggies": "markets"
        }))
	], 
    [ 
        "CA", new Map(Object.entries({
            "Lebanese": "lebanese",
            "Cafes": "cafes",
            "Caribbean": "caribbean",
            "Salad": "salad",
            "Canadian (New)": "newcanadian",
            "Japanese": "japanese",
            "German": "german",
            "Shaved Snow": "shavedsnow",
            "Breakfast & Brunch": "breakfast_brunch",
            "Belgian": "belgian",
            "Do-It-Yourself Food": "diyfood",
            "Vegan": "vegan",
            "Acai Bowls": "acaibowls",
            "Wineries": "wineries",
            "Australian": "australian",
            "Mexican": "mexican",
            "Creperies": "creperies",
            "Coffee & Tea": "coffee",
            "Southern": "southern",
            "Mediterranean": "mediterranean",
            "Custom Cakes": "customcakes",
            "Organic Stores": "organic_stores",
            "Seafood Markets": "seafoodmarkets",
            "Chinese": "chinese",
            "Kebab": "kebab",
            "Kosher": "kosher",
            "Bistros": "bistros",
            "Fondue": "fondue",
            "Fish & Chips": "fishnchips",
            "Food": "food",
            "Fast Food": "hotdogs",
            "Meat Shops": "meats",
            "Poutineries": "poutineries",
            "Ethical Grocery": "ethicgrocery",
            "Hot Dogs": "hotdog",
            "Syrian": "syrian",
            "Cantonese": "cantonese",
            "Butcher": "butcher",
            "Egyptian": "egyptian",
            "Russian": "russian",
            "Food Delivery Services": "fooddeliveryservices",
            "Food Stands": "foodstands",
            "Pakistani": "pakistani",
            "Basque": "basque",
            "Burmese": "burmese",
            "Breweries": "breweries",
            "International Grocery": "intlgrocery",
            "Dumplings": "dumplings",
            "Restaurants": "restaurants",
            "Portuguese": "portuguese",
            "Vegetarian": "vegetarian",
            "Smokehouse": "smokehouse",
            "Wine Tasting Room": "winetastingroom",
            "South African": "southafrican",
            "Italian": "italian",
            "Food Trucks": "foodtrucks",
            "Sugar Shacks": "sugarshacks",
            "Chocolatiers & Shops": "chocolate",
            "Pancakes": "pancakes",
            "Ethiopian": "ethiopian",
            "Beer, Wine & Spirits": "beer_and_wine",
            "Slovakian": "slovakian",
            "Grocery": "grocery",
            "Ramen": "ramen",
            "Afghan": "afghani",
            "Scandinavian": "scandinavian",
            "African": "african",
            "Barbeque": "bbq",
            "Brasseries": "brasseries",
            "Reunion": "reunion",
            "Steakhouses": "steak",
            "Sandwiches": "sandwiches",
            "Candy Stores": "candy",
            "Filipino": "filipino",
            "Convenience Stores": "convenience",
            "Singaporean": "singaporean",
            "Pan Asian": "panasian",
            "Latin American": "latin",
            "Coffee Roasteries": "coffeeroasteries",
            "Nicaraguan": "nicaraguan",
            "Juice Bars & Smoothies": "juicebars",
            "Street Vendors": "streetvendors",
            "Brazilian": "brazilian",
            "Desserts": "desserts",
            "Cideries": "cideries",
            "Hong Kong Style Cafe": "hkcafe",
            "Dinner Theater": "dinnertheater",
            "Colombian": "colombian",
            "Distilleries": "distilleries",
            "Turkish": "turkish",
            "Bubble Tea": "bubbletea",
            "Falafel": "falafel",
            "Venison": "venison",
            "Tea Rooms": "tea",
            "Specialty Food": "gourmet",
            "Food Court": "food_court",
            "Senegalese": "senegalese",
            "Farmers Market": "farmersmarket",
            "Nepalese": "himalayan",
            "Salvadoran": "salvadoran",
            "Hungarian": "hungarian",
            "Laotian": "laotian",
            "Macarons": "macarons",
            "British": "british",
            "French": "french",
            "Taiwanese": "taiwanese",
            "Pop-Up Restaurants": "popuprestaurants",
            "Ice Cream & Frozen Yogurt": "icecream",
            "Poke": "poke",
            "Dim Sum": "dimsum",
            "Ukrainian": "ukrainian",
            "Greek": "greek",
            "Arabic": "arabian",
            "Cake Shop": "cakeshop",
            "Delis": "delis",
            "Scottish": "scottish",
            "Mauritius": "mauritius",
            "Iranian": "persian",
            "Indonesian": "indonesian",
            "Austrian": "austrian",
            "Waffles": "waffles",
            "Themed Cafes": "themedcafes",
            "Imported Food": "importedfood",
            "Donuts": "donuts",
            "American (Traditional)": "tradamerican",
            "Creole": "cajun",
            "Czech": "czech",
            "Iberian": "iberian",
            "Coffee & Tea Supplies": "coffeeteasupplies",
            "Mongolian": "mongolian",
            "Noodles": "noodles",
            "Seafood": "seafood",
            "Gastropubs": "gastropubs",
            "Gluten-Free": "gluten_free",
            "International": "international",
            "Spanish": "spanish",
            "Peruvian": "peruvian",
            "Hawaiian": "hawaiian",
            "Supper Clubs": "supperclubs",
            "Honduran": "honduran",
            "Delicatessen": "delicatessen",
            "Asian Fusion": "asianfusion",
            "Bangladeshi": "bangladeshi",
            "Small Plates": "tapasmallplates",
            "Thai": "thai",
            "Tapas Bars": "tapas",
            "Health Markets": "healthmarkets",
            "Modern European": "modern_european",
            "Middle Eastern": "mideastern",
            "Diners": "diners",
            "Buffets": "buffets",
            "Indian": "indpak",
            "Chicken Shop": "chickenshop",
            "Guamanian": "guamanian",
            "Raw Food": "raw_food",
            "Cambodian": "cambodian",
            "Water Stores": "waterstores",
            "Brewpubs": "brewpubs",
            "Cheese Shops": "cheese",
            "Chicken Wings": "chicken_wings",
            "Polish": "polish",
            "Korean": "korean",
            "Pizza": "pizza",
            "Venezuelan": "venezuelan",
            "Comfort Food": "comfortfood",
            "Argentine": "argentine",
            "Cheesesteaks": "cheesesteaks",
            "Irish": "irish",
            "Sushi Bars": "sushi",
            "Cuban": "cuban",
            "Herbs & Spices": "herbsandspices",
            "Moroccan": "moroccan",
            "Soup": "soup",
            "Donairs": "donairs",
            "Bagels": "bagels",
            "Vietnamese": "vietnamese",
            "Halal": "halal",
            "Soul Food": "soulfood",
            "Hot Pot": "hotpot",
            "Haitian": "haitian",
            "Burgers": "burgers",
            "Internet Cafes": "internetcafe",
            "Bakeries": "bakeries",
            "Malaysian": "malaysian",
            "Sri Lankan": "srilankan",
            "Hakka": "hakka",
            "Fruits & Veggies": "markets"
	    }))
    ]
]);